variable "env" {}
variable "instance_type" {}
variable "ssh_user" {}
variable "ssh_pass" {}
variable "zone_id" {}
variable "vault_token" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
